### ISSUE TITLE
[Update Request] amazongames

### ISSUE THREAD

**Issue by kyau** [RalfEs73/chocolatey-packages#10]
Amazon Games

**Version requested**
2.2.8063.2-OFFICIAL-7d928bec

**Additional notes**
As of 2022-07-29 this is the current file downloaded from `https://download.amazongames.com/AmazonGamesSetup.exe`.
```
    File: AmazonGamesSetup.exe
  CRC-32: 71b066b0
   SHA-1: 383b8b1f5517c856df40eee799ab19689e7bbbbd
 SHA-256: 9dbb71cb9c4bcad710768db6493317ccf31702a6023aed8700209667f0fae547
 SHA-512: 0a9d5998b9719511e75eae2bb331905916e4173b927a0c6afbf633cedfd70d8bc7296042f28df6e3c790e93b040d78c39028c4888f4be783dd54f8059bfdeab9
```

**Comment by RalfEs73** [comment]
Done:
https://community.chocolatey.org/packages/amazongames/2.2.8063.2

**Comment by kyau** [comment]
Thanks for the update.
