### ISSUE TITLE
[Bug] 22.0.0 Movavi ScreenRecorder failed to install

### ISSUE THREAD

**Issue by sgaechter** [RalfEs73/chocolatey-packages#13]
I used the flag "--ignore-checksum
ERROR: The file was a text file but is attempting to be run as an executable - 'C:\Users\sven.gaechter\AppData\Local\Temp\chocolatey\movaviscreenrecorder\22.0.0\downloads-all.html'
The install of movaviscreenrecorder was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\movaviscreenrecorder\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - movaviscreenrecorder (exited 4) - Error while running 'C:\ProgramData\chocolatey\lib\movaviscreenrecorder\tools\chocolateyinstall.ps1'.
 See log for details.

Thanks for fixing.

**Comment by RalfEs73** [comment]
I no longer support the Movavi ScreenRecorder package.
